USE [IBNSINAMAIN]
GO

/****** Object:  StoredProcedure [dbo].[INC_addNewpatiant]    Script Date: 12/17/2019 6:25:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[INC_addNewpatiant]
(
	@CARD_NO nvarchar(100) ,
	@NAME_ARB nvarchar(250) ,
	@NAME_ENG nvarchar(250) ,
	@BIRTHDATE date ,
	@BAGE_NO nvarchar(100) ,
	@C_ID int ,
	@GENDER nvarchar(10) ,
	@NAL_ID int ,
	@PHONE_NO bigint ,
	@CONST_ID int ,
	@EXP_DATE date ,
	@NOTES nvarchar(250) ,
	@P_STATE bit ,
	@NAT_NUMBER bigint ,
    @KID_NO int ,
	@CITY_ID int ,
	@IMAGE_CARD nvarchar(250) ,
	@userId int,
	@userIp nvarchar(50)

)
As
BEGIN TRY
	BEGIN TRANSACTION
		declare @PINC_ID int
		SELECT @PINC_ID = MAX(PINC_ID) FROM [dbo].[INC_PATIANT] 
		SET @PINC_ID = @PINC_ID + 1

		INSERT INTO dbo.INC_PATIANT (PINC_ID,CARD_NO,NAME_ARB,NAME_ENG,BIRTHDATE,BAGE_NO,C_ID,GENDER,NAL_ID,PHONE_NO,CONST_ID,EXP_DATE,NOTES,P_STATE,NAT_NUMBER,KID_NO,CITY_ID,IMAGE_CARD,USER_ID,USER_IP) VALUES (@PINC_ID,@CARD_NO,@NAME_ARB,@NAME_ENG,@BIRTHDATE,@BAGE_NO,@C_ID,@GENDER,@NAL_ID,@PHONE_NO,@CONST_ID,@EXP_DATE,@NOTES,@P_STATE,@NAT_NUMBER,@KID_NO,@CITY_ID,@IMAGE_CARD,@userId,@userIp)


		COMMIT TRANSACTION
END TRY

BEGIN CATCH

	if @@ERROR <> 0
		ROLLBACK TRANSACTION;

END CATCH
GO


