USE [IBNSINAMAIN]
GO

/****** Object:  Table [dbo].[INC_CLINIC_GROUP]    Script Date: 12/17/2019 6:20:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INC_CLINIC_GROUP](
	[group_no] [int] IDENTITY(1,1) NOT NULL,
	[max_value] [money] NULL,
	[per_t] [int] NULL,
 CONSTRAINT [PK_INC_CLINIC_GROUP] PRIMARY KEY CLUSTERED 
(
	[group_no] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


