USE [DB_A41508_ibn]
GO

/****** Object:  Table [dbo].[INC_SERVICES_RESTRICTIONS]    Script Date: 1/22/2020 6:25:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INC_SERVICES_RESTRICTIONS](
	[n] [int] IDENTITY(1,1) NOT NULL,
	[C_ID] [int] NULL,
	[CLINIC_ID] [int] NULL,
	[Service_ID] [int] NULL,
	[CONTRACT_NO] [int] NULL,
	[MAX_VALUE] [decimal](18, 3) NULL,
	[SERVICE_STS] [bit] NULL,
	[USER_ID] [int] NULL,
	[USER_DT] [date] NULL,
	[USER_IP] [nvarchar](50) NULL,
 CONSTRAINT [PK_INC_SERVICES_RESTRICTIONS_1] PRIMARY KEY CLUSTERED 
(
	[n] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[INC_SERVICES_RESTRICTIONS] ADD  CONSTRAINT [DF_INC_SERVICES_RESTRICTIONS_USER_DT]  DEFAULT (getdate()) FOR [USER_DT]
GO


